spring:
  application:
    name: eureka-server
  devtools:
   restart:
     enabled: true
     additional-paths: eureka-service-sn\src\main\java

#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java

server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false # 本地调试环境下关闭自我保护机制
  instance:
    hostname: localhost
    #prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
