spring:
  application:
    name: eureka-service-ha
server:
  port: 8761
eureka:
  instance:
    # when profile=peer1, hostname=peer1
    hostname: peer1
  client:
    register-with-eureka: false #1
    fetch-registry: false  #2
    service-url:
      defaultZone: http://peer2:8762/eureka/
